# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: positionModel.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='positionModel.proto',
  package='demoposition',
  syntax='proto3',
  serialized_options=b'\252\002\'Position4All.DemoPublishingApp.Messages',
  serialized_pb=b'\n\x13positionModel.proto\x12\x0c\x64\x65moposition\"d\n\x08Position\x12\x10\n\x08Latitude\x18\x01 \x01(\x01\x12\x11\n\tLongitude\x18\x02 \x01(\x01\x12\x10\n\x08\x41ltitude\x18\x03 \x01(\x01\x12\x0f\n\x07Heading\x18\x04 \x01(\x01\x12\x10\n\x08Velocity\x18\x05 \x01(\x01\"\xc7\x01\n\x05State\x12+\n\x0bOwnPosition\x18\x01 \x01(\x0b\x32\x16.demoposition.Position\x12/\n\x0fTarget1Position\x18\x02 \x01(\x0b\x32\x16.demoposition.Position\x12/\n\x0fTarget2Position\x18\x03 \x01(\x0b\x32\x16.demoposition.Position\x12/\n\x0fTarget3Position\x18\x04 \x01(\x0b\x32\x16.demoposition.PositionB*\xaa\x02\'Position4All.DemoPublishingApp.Messagesb\x06proto3'
)




_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='demoposition.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Latitude', full_name='demoposition.Position.Latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Longitude', full_name='demoposition.Position.Longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Altitude', full_name='demoposition.Position.Altitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Heading', full_name='demoposition.Position.Heading', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Velocity', full_name='demoposition.Position.Velocity', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=137,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='demoposition.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='OwnPosition', full_name='demoposition.State.OwnPosition', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Target1Position', full_name='demoposition.State.Target1Position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Target2Position', full_name='demoposition.State.Target2Position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Target3Position', full_name='demoposition.State.Target3Position', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=339,
)

_STATE.fields_by_name['OwnPosition'].message_type = _POSITION
_STATE.fields_by_name['Target1Position'].message_type = _POSITION
_STATE.fields_by_name['Target2Position'].message_type = _POSITION
_STATE.fields_by_name['Target3Position'].message_type = _POSITION
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'positionModel_pb2'
  # @@protoc_insertion_point(class_scope:demoposition.Position)
  })
_sym_db.RegisterMessage(Position)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'positionModel_pb2'
  # @@protoc_insertion_point(class_scope:demoposition.State)
  })
_sym_db.RegisterMessage(State)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
